<?php
$pokemon_attacks = [['id'=>'1','name'=>'Pound','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'35','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'2','name'=>'Karate Chop*','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'25','power'=>'50','accuracy'=>'1','generation'=>'I'],
['id'=>'3','name'=>'Double Slap','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'10','power'=>'15','accuracy'=>'0,85','generation'=>'I'],
['id'=>'4','name'=>'Comet Punch','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'18','accuracy'=>'0,85','generation'=>'I'],
['id'=>'5','name'=>'Mega Punch','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'80','accuracy'=>'0,85','generation'=>'I'],
['id'=>'6','name'=>'Pay Day','type_1'=>'Normal','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'7','name'=>'Fire Punch','type_1'=>'Fire','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'75','accuracy'=>'1','generation'=>'I'],
['id'=>'8','name'=>'Ice Punch','type_1'=>'Ice','category'=>'Physical','contest'=>'Beautiful','pp'=>'15','power'=>'75','accuracy'=>'1','generation'=>'I'],
['id'=>'9','name'=>'Thunder Punch','type_1'=>'Electric','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'75','accuracy'=>'1','generation'=>'I'],
['id'=>'10','name'=>'Scratch','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'35','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'11','name'=>'Vise Grip','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'30','power'=>'55','accuracy'=>'1','generation'=>'I'],
['id'=>'12','name'=>'Guillotine','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'0','accuracy'=>'0,3','generation'=>'I'],
['id'=>'13','name'=>'Razor Wind','type_1'=>'Normal','category'=>'Special','contest'=>'Cool','pp'=>'10','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'14','name'=>'Swords Dance','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'15','name'=>'Cut','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'30','power'=>'50','accuracy'=>'0,95','generation'=>'I'],
['id'=>'16','name'=>'Gust*','type_1'=>'Flying','category'=>'Special','contest'=>'Clever','pp'=>'35','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'17','name'=>'Wing Attack','type_1'=>'Flying','category'=>'Physical','contest'=>'Cool','pp'=>'35','power'=>'60','accuracy'=>'1','generation'=>'I'],
['id'=>'18','name'=>'Whirlwind','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'19','name'=>'Fly','type_1'=>'Flying','category'=>'Physical','contest'=>'Clever','pp'=>'15','power'=>'90','accuracy'=>'0,95','generation'=>'I'],
['id'=>'20','name'=>'Bind','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'15','accuracy'=>'85','generation'=>'I'],
['id'=>'21','name'=>'Slam','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'80','accuracy'=>'0,75','generation'=>'I'],
['id'=>'22','name'=>'Vine Whip','type_1'=>'Grass','category'=>'Physical','contest'=>'Cool','pp'=>'25','power'=>'45','accuracy'=>'1','generation'=>'I'],
['id'=>'23','name'=>'Stomp','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'24','name'=>'Double Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'30','power'=>'30','accuracy'=>'1','generation'=>'I'],
['id'=>'25','name'=>'Mega Kick','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'120','accuracy'=>'0,75','generation'=>'I'],
['id'=>'26','name'=>'Jump Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'100','accuracy'=>'0,95','generation'=>'I'],
['id'=>'27','name'=>'Rolling Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'60','accuracy'=>'0,85','generation'=>'I'],
['id'=>'28','name'=>'Sand Attack*','type_1'=>'Ground','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'29','name'=>'Headbutt','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'70','accuracy'=>'1','generation'=>'I'],
['id'=>'30','name'=>'Horn Attack','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'25','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'31','name'=>'Fury Attack','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'15','accuracy'=>'0,85','generation'=>'I'],
['id'=>'32','name'=>'Horn Drill','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'0','accuracy'=>'0,3','generation'=>'I'],
['id'=>'33','name'=>'Tackle','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'35','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'34','name'=>'Body Slam','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'85','accuracy'=>'1','generation'=>'I'],
['id'=>'35','name'=>'Wrap','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'15','accuracy'=>'0,9','generation'=>'I'],
['id'=>'36','name'=>'Take Down','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'90','accuracy'=>'0,85','generation'=>'I'],
['id'=>'37','name'=>'Thrash','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'120','accuracy'=>'1','generation'=>'I'],
['id'=>'38','name'=>'Double-Edge','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'120','accuracy'=>'1','generation'=>'I'],
['id'=>'39','name'=>'Tail Whip','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'30','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'40','name'=>'Poison Sting','type_1'=>'Poison','category'=>'Physical','contest'=>'Clever','pp'=>'35','power'=>'115','accuracy'=>'1','generation'=>'I'],
['id'=>'41','name'=>'Twineedle','type_1'=>'Bug','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'25','accuracy'=>'1','generation'=>'I'],
['id'=>'42','name'=>'Pin Missile','type_1'=>'Bug','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'25','accuracy'=>'0,95','generation'=>'I'],
['id'=>'43','name'=>'Leer','type_1'=>'Normal','category'=>'Status','contest'=>'Cool','pp'=>'30','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'44','name'=>'Bite*','type_1'=>'Dark','category'=>'Physical','contest'=>'Tough','pp'=>'25','power'=>'60','accuracy'=>'1','generation'=>'I'],
['id'=>'45','name'=>'Growl','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'40','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'46','name'=>'Roar','type_1'=>'Normal','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'47','name'=>'Sing','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'0,55','generation'=>'I'],
['id'=>'48','name'=>'Supersonic','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0,55','generation'=>'I'],
['id'=>'49','name'=>'Sonic Boom','type_1'=>'Normal','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'','accuracy'=>'0,9','generation'=>'I'],
['id'=>'50','name'=>'Disable','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'51','name'=>'Acid','type_1'=>'Poison','category'=>'Special','contest'=>'Clever','pp'=>'30','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'52','name'=>'Ember','type_1'=>'Fire','category'=>'Special','contest'=>'Cute','pp'=>'25','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'53','name'=>'Flamethrower','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'90','accuracy'=>'1','generation'=>'I'],
['id'=>'54','name'=>'Mist','type_1'=>'Ice','category'=>'Status','contest'=>'Beautiful','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'55','name'=>'Water Gun','type_1'=>'Water','category'=>'Special','contest'=>'Cute','pp'=>'25','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'56','name'=>'Hydro Pump','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'110','accuracy'=>'0,8','generation'=>'I'],
['id'=>'57','name'=>'Surf','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'90','accuracy'=>'1','generation'=>'I'],
['id'=>'58','name'=>'Ice Beam','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'10','power'=>'90','accuracy'=>'1','generation'=>'I'],
['id'=>'59','name'=>'Blizzard','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'110','accuracy'=>'0,7','generation'=>'I'],
['id'=>'60','name'=>'Psybeam','type_1'=>'Psychic','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'61','name'=>'Bubble Beam','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'62','name'=>'Aurora Beam','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'63','name'=>'Hyper Beam','type_1'=>'Normal','category'=>'Special','contest'=>'Cool','pp'=>'5','power'=>'150','accuracy'=>'0,9','generation'=>'I'],
['id'=>'64','name'=>'Peck','type_1'=>'Flying','category'=>'Physical','contest'=>'Cool','pp'=>'35','power'=>'35','accuracy'=>'1','generation'=>'I'],
['id'=>'65','name'=>'Drill Peck','type_1'=>'Flying','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'66','name'=>'Submission','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'80','accuracy'=>'0,8','generation'=>'I'],
['id'=>'67','name'=>'Low Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'68','name'=>'Counter','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'69','name'=>'Seismic Toss','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'70','name'=>'Strength','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'71','name'=>'Absorb','type_1'=>'Grass','category'=>'Special','contest'=>'Clever','pp'=>'25','power'=>'20','accuracy'=>'1','generation'=>'I'],
['id'=>'72','name'=>'Mega Drain','type_1'=>'Grass','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'73','name'=>'Leech Seed','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0,9','generation'=>'I'],
['id'=>'74','name'=>'Growth','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'75','name'=>'Razor Leaf','type_1'=>'Grass','category'=>'Physical','contest'=>'Cool','pp'=>'25','power'=>'55','accuracy'=>'0,95','generation'=>'I'],
['id'=>'76','name'=>'Solar Beam','type_1'=>'Grass','category'=>'Special','contest'=>'Cool','pp'=>'10','power'=>'120','accuracy'=>'1','generation'=>'I'],
['id'=>'77','name'=>'Poison Powder','type_1'=>'Poison','category'=>'Status','contest'=>'Clever','pp'=>'35','power'=>'0','accuracy'=>'0,75','generation'=>'I'],
['id'=>'78','name'=>'Stun Spore','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'30','power'=>'0','accuracy'=>'0,75','generation'=>'I'],
['id'=>'79','name'=>'Sleep Powder','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'0,75','generation'=>'I'],
['id'=>'80','name'=>'Petal Dance','type_1'=>'Grass','category'=>'Special','contest'=>'Beautiful','pp'=>'10','power'=>'120','accuracy'=>'1','generation'=>'I'],
['id'=>'81','name'=>'String Shot','type_1'=>'Bug','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0,95','generation'=>'I'],
['id'=>'82','name'=>'Dragon Rage','type_1'=>'Dragon','category'=>'Special','contest'=>'Cool','pp'=>'10','power'=>'','accuracy'=>'1','generation'=>'I'],
['id'=>'83','name'=>'Fire Spin','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'35','accuracy'=>'0,85','generation'=>'I'],
['id'=>'84','name'=>'Thunder Shock','type_1'=>'Electric','category'=>'Special','contest'=>'Cool','pp'=>'30','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'85','name'=>'Thunderbolt','type_1'=>'Electric','category'=>'Special','contest'=>'Cool','pp'=>'15','power'=>'90','accuracy'=>'1','generation'=>'I'],
['id'=>'86','name'=>'Thunder Wave','type_1'=>'Electric','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0,9','generation'=>'I'],
['id'=>'87','name'=>'Thunder','type_1'=>'Electric','category'=>'Special','contest'=>'Cool','pp'=>'10','power'=>'110','accuracy'=>'0,7','generation'=>'I'],
['id'=>'88','name'=>'Rock Throw','type_1'=>'Rock','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'50','accuracy'=>'0,9','generation'=>'I'],
['id'=>'89','name'=>'Earthquake','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'100','accuracy'=>'1','generation'=>'I'],
['id'=>'90','name'=>'Fissure','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'5','power'=>'0','accuracy'=>'0,3','generation'=>'I'],
['id'=>'91','name'=>'Dig','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'92','name'=>'Toxic','type_1'=>'Poison','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0,9','generation'=>'I'],
['id'=>'93','name'=>'Confusion','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'25','power'=>'50','accuracy'=>'1','generation'=>'I'],
['id'=>'94','name'=>'Psychic','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'10','power'=>'90','accuracy'=>'1','generation'=>'I'],
['id'=>'95','name'=>'Hypnosis','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0,6','generation'=>'I'],
['id'=>'96','name'=>'Meditate','type_1'=>'Psychic','category'=>'Status','contest'=>'Beautiful','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'97','name'=>'Agility','type_1'=>'Psychic','category'=>'Status','contest'=>'Cool','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'98','name'=>'Quick Attack','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'30','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'99','name'=>'Rage','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'20','accuracy'=>'1','generation'=>'I'],
['id'=>'100','name'=>'Teleport','type_1'=>'Psychic','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'101','name'=>'Night Shade','type_1'=>'Ghost','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'102','name'=>'Mimic','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'103','name'=>'Screech','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0,85','generation'=>'I'],
['id'=>'104','name'=>'Double Team','type_1'=>'Normal','category'=>'Status','contest'=>'Cool','pp'=>'15','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'105','name'=>'Recover','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'106','name'=>'Harden','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'107','name'=>'Minimize','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'108','name'=>'Smokescreen','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'109','name'=>'Confuse Ray','type_1'=>'Ghost','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'110','name'=>'Withdraw','type_1'=>'Water','category'=>'Status','contest'=>'Cute','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'111','name'=>'Defense Curl','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'112','name'=>'Barrier','type_1'=>'Psychic','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'113','name'=>'Light Screen','type_1'=>'Psychic','category'=>'Status','contest'=>'Beautiful','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'114','name'=>'Haze','type_1'=>'Ice','category'=>'Status','contest'=>'Beautiful','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'115','name'=>'Reflect','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'116','name'=>'Focus Energy','type_1'=>'Normal','category'=>'Status','contest'=>'Cool','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'117','name'=>'Bide','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'118','name'=>'Metronome','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'119','name'=>'Mirror Move','type_1'=>'Flying','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'120','name'=>'Self-Destruct','type_1'=>'Normal','category'=>'Physical','contest'=>'Beautiful','pp'=>'5','power'=>'200','accuracy'=>'1','generation'=>'I'],
['id'=>'121','name'=>'Egg Bomb','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'10','power'=>'100','accuracy'=>'0,75','generation'=>'I'],
['id'=>'122','name'=>'Lick','type_1'=>'Ghost','category'=>'Physical','contest'=>'Cute','pp'=>'30','power'=>'30','accuracy'=>'1','generation'=>'I'],
['id'=>'123','name'=>'Smog','type_1'=>'Poison','category'=>'Special','contest'=>'Tough','pp'=>'20','power'=>'30','accuracy'=>'0,7','generation'=>'I'],
['id'=>'124','name'=>'Sludge','type_1'=>'Poison','category'=>'Special','contest'=>'Tough','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'I'],
['id'=>'125','name'=>'Bone Club','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'65','accuracy'=>'0,85','generation'=>'I'],
['id'=>'126','name'=>'Fire Blast','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'110','accuracy'=>'0,85','generation'=>'I'],
['id'=>'127','name'=>'Waterfall','type_1'=>'Water','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'128','name'=>'Clamp','type_1'=>'Water','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'35','accuracy'=>'0,85','generation'=>'I'],
['id'=>'129','name'=>'Swift','type_1'=>'Normal','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'I'],
['id'=>'130','name'=>'Skull Bash','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'130','accuracy'=>'1','generation'=>'I'],
['id'=>'131','name'=>'Spike Cannon','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'20','accuracy'=>'1','generation'=>'I'],
['id'=>'132','name'=>'Constrict','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'35','power'=>'10','accuracy'=>'1','generation'=>'I'],
['id'=>'133','name'=>'Amnesia','type_1'=>'Psychic','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'134','name'=>'Kinesis','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'0,8','generation'=>'I'],
['id'=>'135','name'=>'Soft-Boiled','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'136','name'=>'High Jump Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'130','accuracy'=>'0,9','generation'=>'I'],
['id'=>'137','name'=>'Glare','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'30','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'138','name'=>'Dream Eater','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'100','accuracy'=>'1','generation'=>'I'],
['id'=>'139','name'=>'Poison Gas','type_1'=>'Poison','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0,9','generation'=>'I'],
['id'=>'140','name'=>'Barrage','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'20','power'=>'15','accuracy'=>'0,85','generation'=>'I'],
['id'=>'141','name'=>'Leech Life','type_1'=>'Bug','category'=>'Physical','contest'=>'Clever','pp'=>'10','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'142','name'=>'Lovely Kiss','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'10','power'=>'0','accuracy'=>'0,75','generation'=>'I'],
['id'=>'143','name'=>'Sky Attack','type_1'=>'Flying','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'140','accuracy'=>'0,9','generation'=>'I'],
['id'=>'144','name'=>'Transform','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'145','name'=>'Bubble','type_1'=>'Water','category'=>'Special','contest'=>'Cute','pp'=>'30','power'=>'40','accuracy'=>'1','generation'=>'I'],
['id'=>'146','name'=>'Dizzy Punch','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'10','power'=>'70','accuracy'=>'1','generation'=>'I'],
['id'=>'147','name'=>'Spore','type_1'=>'Grass','category'=>'Status','contest'=>'Beautiful','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'148','name'=>'Flash','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'149','name'=>'Psywave','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'I'],
['id'=>'150','name'=>'Splash','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'151','name'=>'Acid Armor','type_1'=>'Poison','category'=>'Status','contest'=>'Tough','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'152','name'=>'Crabhammer','type_1'=>'Water','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'100','accuracy'=>'0,9','generation'=>'I'],
['id'=>'153','name'=>'Explosion','type_1'=>'Normal','category'=>'Physical','contest'=>'Beautiful','pp'=>'5','power'=>'250','accuracy'=>'1','generation'=>'I'],
['id'=>'154','name'=>'Fury Swipes','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'18','accuracy'=>'0,8','generation'=>'I'],
['id'=>'155','name'=>'Bonemerang','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'50','accuracy'=>'0,9','generation'=>'I'],
['id'=>'156','name'=>'Rest','type_1'=>'Psychic','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'157','name'=>'Rock Slide','type_1'=>'Rock','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'75','accuracy'=>'0,9','generation'=>'I'],
['id'=>'158','name'=>'Hyper Fang','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'80','accuracy'=>'0,9','generation'=>'I'],
['id'=>'159','name'=>'Sharpen','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'160','name'=>'Conversion','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'161','name'=>'Tri Attack','type_1'=>'Normal','category'=>'Special','contest'=>'Beautiful','pp'=>'10','power'=>'80','accuracy'=>'1','generation'=>'I'],
['id'=>'162','name'=>'Super Fang','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0,9','generation'=>'I'],
['id'=>'163','name'=>'Slash','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'70','accuracy'=>'1','generation'=>'I'],
['id'=>'164','name'=>'Substitute','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'I'],
['id'=>'165','name'=>'Struggle','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'1','power'=>'50','accuracy'=>'0','generation'=>'I'],
['id'=>'166','name'=>'Sketch','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'1','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'167','name'=>'Triple Kick','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'10','accuracy'=>'0,9','generation'=>'II'],
['id'=>'168','name'=>'Thief','type_1'=>'Dark','category'=>'Physical','contest'=>'Tough','pp'=>'25','power'=>'60','accuracy'=>'1','generation'=>'II'],
['id'=>'169','name'=>'Spider Web','type_1'=>'Bug','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'170','name'=>'Mind Reader','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'171','name'=>'Nightmare','type_1'=>'Ghost','category'=>'Status','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'172','name'=>'Flame Wheel','type_1'=>'Fire','category'=>'Physical','contest'=>'Beautiful','pp'=>'25','power'=>'60','accuracy'=>'1','generation'=>'II'],
['id'=>'173','name'=>'Snore','type_1'=>'Normal','category'=>'Special','contest'=>'Cute','pp'=>'15','power'=>'50','accuracy'=>'1','generation'=>'II'],
['id'=>'174','name'=>'Curse*','type_1'=>'Ghost','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'175','name'=>'Flail','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'176','name'=>'Conversion 2','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'30','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'177','name'=>'Aeroblast','type_1'=>'Flying','category'=>'Special','contest'=>'Cool','pp'=>'5','power'=>'100','accuracy'=>'0,95','generation'=>'II'],
['id'=>'178','name'=>'Cotton Spore','type_1'=>'Grass','category'=>'Status','contest'=>'Beautiful','pp'=>'40','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'179','name'=>'Reversal','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'180','name'=>'Spite','type_1'=>'Ghost','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'181','name'=>'Powder Snow','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'25','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'182','name'=>'Protect','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'183','name'=>'Mach Punch','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'30','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'184','name'=>'Scary Face','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'185','name'=>'Feint Attack','type_1'=>'Dark','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'II'],
['id'=>'186','name'=>'Sweet Kiss*','type_1'=>'Fairy','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0,75','generation'=>'II'],
['id'=>'187','name'=>'Belly Drum','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'188','name'=>'Sludge Bomb','type_1'=>'Poison','category'=>'Special','contest'=>'Tough','pp'=>'10','power'=>'90','accuracy'=>'1','generation'=>'II'],
['id'=>'189','name'=>'Mud-Slap','type_1'=>'Ground','category'=>'Special','contest'=>'Cute','pp'=>'10','power'=>'20','accuracy'=>'1','generation'=>'II'],
['id'=>'190','name'=>'Octazooka','type_1'=>'Water','category'=>'Special','contest'=>'Tough','pp'=>'10','power'=>'65','accuracy'=>'0,85','generation'=>'II'],
['id'=>'191','name'=>'Spikes','type_1'=>'Ground','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'192','name'=>'Zap Cannon','type_1'=>'Electric','category'=>'Special','contest'=>'Cool','pp'=>'5','power'=>'120','accuracy'=>'0,5','generation'=>'II'],
['id'=>'193','name'=>'Foresight','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'194','name'=>'Destiny Bond','type_1'=>'Ghost','category'=>'Status','contest'=>'Clever','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'195','name'=>'Perish Song','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'196','name'=>'Icy Wind','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'55','accuracy'=>'0,95','generation'=>'II'],
['id'=>'197','name'=>'Detect','type_1'=>'Fighting','category'=>'Status','contest'=>'Cool','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'198','name'=>'Bone Rush','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'25','accuracy'=>'0,9','generation'=>'II'],
['id'=>'199','name'=>'Lock-On','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'200','name'=>'Outrage','type_1'=>'Dragon','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'120','accuracy'=>'1','generation'=>'II'],
['id'=>'201','name'=>'Sandstorm','type_1'=>'Rock','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'202','name'=>'Giga Drain','type_1'=>'Grass','category'=>'Special','contest'=>'Clever','pp'=>'10','power'=>'75','accuracy'=>'1','generation'=>'II'],
['id'=>'203','name'=>'Endure','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'204','name'=>'Charm*','type_1'=>'Fairy','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'205','name'=>'Rollout','type_1'=>'Rock','category'=>'Physical','contest'=>'Cute','pp'=>'20','power'=>'30','accuracy'=>'0,9','generation'=>'II'],
['id'=>'206','name'=>'False Swipe','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'40','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'207','name'=>'Swagger','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'0,85','generation'=>'II'],
['id'=>'208','name'=>'Milk Drink','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'209','name'=>'Spark','type_1'=>'Electric','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'II'],
['id'=>'210','name'=>'Fury Cutter','type_1'=>'Bug','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'40','accuracy'=>'0,95','generation'=>'II'],
['id'=>'211','name'=>'Steel Wing','type_1'=>'Steel','category'=>'Physical','contest'=>'Cool','pp'=>'25','power'=>'70','accuracy'=>'0,9','generation'=>'II'],
['id'=>'212','name'=>'Mean Look','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'213','name'=>'Attract','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'214','name'=>'Sleep Talk','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'215','name'=>'Heal Bell','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'216','name'=>'Return','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'217','name'=>'Present','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'0,9','generation'=>'II'],
['id'=>'218','name'=>'Frustration','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'219','name'=>'Safeguard','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'25','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'220','name'=>'Pain Split','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'221','name'=>'Sacred Fire','type_1'=>'Fire','category'=>'Physical','contest'=>'Beautiful','pp'=>'5','power'=>'100','accuracy'=>'0,95','generation'=>'II'],
['id'=>'222','name'=>'Magnitude','type_1'=>'Ground','category'=>'Physical','contest'=>'Tough','pp'=>'30','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'223','name'=>'Dynamic Punch','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'100','accuracy'=>'0,5','generation'=>'II'],
['id'=>'224','name'=>'Megahorn','type_1'=>'Bug','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'120','accuracy'=>'0,85','generation'=>'II'],
['id'=>'225','name'=>'Dragon Breath','type_1'=>'Dragon','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'60','accuracy'=>'1','generation'=>'II'],
['id'=>'226','name'=>'Baton Pass','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'227','name'=>'Encore','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'5','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'228','name'=>'Pursuit','type_1'=>'Dark','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'229','name'=>'Rapid Spin','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'40','power'=>'50','accuracy'=>'1','generation'=>'II'],
['id'=>'230','name'=>'Sweet Scent','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'231','name'=>'Iron Tail','type_1'=>'Steel','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'100','accuracy'=>'0,75','generation'=>'II'],
['id'=>'232','name'=>'Metal Claw','type_1'=>'Steel','category'=>'Physical','contest'=>'Cool','pp'=>'35','power'=>'50','accuracy'=>'0,95','generation'=>'II'],
['id'=>'233','name'=>'Vital Throw','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'70','accuracy'=>'0','generation'=>'II'],
['id'=>'234','name'=>'Morning Sun','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'235','name'=>'Synthesis','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'236','name'=>'Moonlight*','type_1'=>'Fairy','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'237','name'=>'Hidden Power','type_1'=>'Normal','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'60','accuracy'=>'1','generation'=>'II'],
['id'=>'238','name'=>'Cross Chop','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'100','accuracy'=>'0,8','generation'=>'II'],
['id'=>'239','name'=>'Twister','type_1'=>'Dragon','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'240','name'=>'Rain Dance','type_1'=>'Water','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'241','name'=>'Sunny Day','type_1'=>'Fire','category'=>'Status','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'242','name'=>'Crunch','type_1'=>'Dark','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'80','accuracy'=>'1','generation'=>'II'],
['id'=>'243','name'=>'Mirror Coat','type_1'=>'Psychic','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'244','name'=>'Psych Up','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'II'],
['id'=>'245','name'=>'Extreme Speed','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'5','power'=>'80','accuracy'=>'1','generation'=>'II'],
['id'=>'246','name'=>'Ancient Power','type_1'=>'Rock','category'=>'Special','contest'=>'Tough','pp'=>'5','power'=>'60','accuracy'=>'1','generation'=>'II'],
['id'=>'247','name'=>'Shadow Ball','type_1'=>'Ghost','category'=>'Special','contest'=>'Clever','pp'=>'15','power'=>'80','accuracy'=>'1','generation'=>'II'],
['id'=>'248','name'=>'Future Sight','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'10','power'=>'120','accuracy'=>'1','generation'=>'II'],
['id'=>'249','name'=>'Rock Smash','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'15','power'=>'40','accuracy'=>'1','generation'=>'II'],
['id'=>'250','name'=>'Whirlpool','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'35','accuracy'=>'0,85','generation'=>'II'],
['id'=>'251','name'=>'Beat Up','type_1'=>'Dark','category'=>'Physical','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'II'],
['id'=>'252','name'=>'Fake Out','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'10','power'=>'40','accuracy'=>'1','generation'=>'III'],
['id'=>'253','name'=>'Uproar','type_1'=>'Normal','category'=>'Special','contest'=>'Cute','pp'=>'10','power'=>'90','accuracy'=>'1','generation'=>'III'],
['id'=>'254','name'=>'Stockpile','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'255','name'=>'Spit Up','type_1'=>'Normal','category'=>'Special','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'256','name'=>'Swallow','type_1'=>'Normal','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'257','name'=>'Heat Wave','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'10','power'=>'95','accuracy'=>'0,9','generation'=>'III'],
['id'=>'258','name'=>'Hail','type_1'=>'Ice','category'=>'Status','contest'=>'Beautiful','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'259','name'=>'Torment','type_1'=>'Dark','category'=>'Status','contest'=>'Tough','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'260','name'=>'Flatter','type_1'=>'Dark','category'=>'Status','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'261','name'=>'Will-O-Wisp','type_1'=>'Fire','category'=>'Status','contest'=>'Beautiful','pp'=>'15','power'=>'0','accuracy'=>'0,85','generation'=>'III'],
['id'=>'262','name'=>'Memento','type_1'=>'Dark','category'=>'Status','contest'=>'Tough','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'263','name'=>'Facade','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'20','power'=>'70','accuracy'=>'1','generation'=>'III'],
['id'=>'264','name'=>'Focus Punch','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'150','accuracy'=>'1','generation'=>'III'],
['id'=>'265','name'=>'Smelling Salts','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'70','accuracy'=>'1','generation'=>'III'],
['id'=>'266','name'=>'Follow Me','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'267','name'=>'Nature Power','type_1'=>'Normal','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'268','name'=>'Charge','type_1'=>'Electric','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'269','name'=>'Taunt','type_1'=>'Dark','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'270','name'=>'Helping Hand','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'271','name'=>'Trick','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'272','name'=>'Role Play','type_1'=>'Psychic','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'273','name'=>'Wish','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'274','name'=>'Assist','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'275','name'=>'Ingrain','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'276','name'=>'Superpower','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'5','power'=>'120','accuracy'=>'1','generation'=>'III'],
['id'=>'277','name'=>'Magic Coat','type_1'=>'Psychic','category'=>'Status','contest'=>'Beautiful','pp'=>'15','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'278','name'=>'Recycle','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'279','name'=>'Revenge','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'60','accuracy'=>'1','generation'=>'III'],
['id'=>'280','name'=>'Brick Break','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'75','accuracy'=>'1','generation'=>'III'],
['id'=>'281','name'=>'Yawn','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'282','name'=>'Knock Off','type_1'=>'Dark','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'65','accuracy'=>'1','generation'=>'III'],
['id'=>'283','name'=>'Endeavor','type_1'=>'Normal','category'=>'Physical','contest'=>'Tough','pp'=>'5','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'284','name'=>'Eruption','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'150','accuracy'=>'1','generation'=>'III'],
['id'=>'285','name'=>'Skill Swap','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'286','name'=>'Imprison','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'287','name'=>'Refresh','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'288','name'=>'Grudge','type_1'=>'Ghost','category'=>'Status','contest'=>'Tough','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'289','name'=>'Snatch','type_1'=>'Dark','category'=>'Status','contest'=>'Clever','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'290','name'=>'Secret Power','type_1'=>'Normal','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'70','accuracy'=>'1','generation'=>'III'],
['id'=>'291','name'=>'Dive','type_1'=>'Water','category'=>'Physical','contest'=>'Beautiful','pp'=>'10','power'=>'80','accuracy'=>'1','generation'=>'III'],
['id'=>'292','name'=>'Arm Thrust','type_1'=>'Fighting','category'=>'Physical','contest'=>'Tough','pp'=>'20','power'=>'15','accuracy'=>'1','generation'=>'III'],
['id'=>'293','name'=>'Camouflage','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'294','name'=>'Tail Glow','type_1'=>'Bug','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'295','name'=>'Luster Purge','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'5','power'=>'70','accuracy'=>'1','generation'=>'III'],
['id'=>'296','name'=>'Mist Ball','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'5','power'=>'70','accuracy'=>'1','generation'=>'III'],
['id'=>'297','name'=>'Feather Dance','type_1'=>'Flying','category'=>'Status','contest'=>'Beautiful','pp'=>'15','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'298','name'=>'Teeter Dance','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'299','name'=>'Blaze Kick','type_1'=>'Fire','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'85','accuracy'=>'0,9','generation'=>'III'],
['id'=>'300','name'=>'Mud Sport','type_1'=>'Ground','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'301','name'=>'Ice Ball','type_1'=>'Ice','category'=>'Physical','contest'=>'Beautiful','pp'=>'20','power'=>'30','accuracy'=>'0,9','generation'=>'III'],
['id'=>'302','name'=>'Needle Arm','type_1'=>'Grass','category'=>'Physical','contest'=>'Clever','pp'=>'15','power'=>'60','accuracy'=>'1','generation'=>'III'],
['id'=>'303','name'=>'Slack Off','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'10','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'304','name'=>'Hyper Voice','type_1'=>'Normal','category'=>'Special','contest'=>'Cool','pp'=>'10','power'=>'90','accuracy'=>'1','generation'=>'III'],
['id'=>'305','name'=>'Poison Fang','type_1'=>'Poison','category'=>'Physical','contest'=>'Clever','pp'=>'15','power'=>'50','accuracy'=>'1','generation'=>'III'],
['id'=>'306','name'=>'Crush Claw','type_1'=>'Normal','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'75','accuracy'=>'0,95','generation'=>'III'],
['id'=>'307','name'=>'Blast Burn','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'150','accuracy'=>'0,9','generation'=>'III'],
['id'=>'308','name'=>'Hydro Cannon','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'150','accuracy'=>'0,9','generation'=>'III'],
['id'=>'309','name'=>'Meteor Mash','type_1'=>'Steel','category'=>'Physical','contest'=>'Cool','pp'=>'10','power'=>'90','accuracy'=>'0,9','generation'=>'III'],
['id'=>'310','name'=>'Astonish','type_1'=>'Ghost','category'=>'Physical','contest'=>'Cute','pp'=>'15','power'=>'30','accuracy'=>'1','generation'=>'III'],
['id'=>'311','name'=>'Weather Ball','type_1'=>'Normal','category'=>'Special','contest'=>'Beautiful','pp'=>'10','power'=>'50','accuracy'=>'1','generation'=>'III'],
['id'=>'312','name'=>'Aromatherapy','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'313','name'=>'Fake Tears','type_1'=>'Dark','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'314','name'=>'Air Cutter','type_1'=>'Flying','category'=>'Special','contest'=>'Cool','pp'=>'25','power'=>'60','accuracy'=>'0,95','generation'=>'III'],
['id'=>'315','name'=>'Overheat','type_1'=>'Fire','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'130','accuracy'=>'0,9','generation'=>'III'],
['id'=>'316','name'=>'Odor Sleuth','type_1'=>'Normal','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'317','name'=>'Rock Tomb','type_1'=>'Rock','category'=>'Physical','contest'=>'Clever','pp'=>'15','power'=>'60','accuracy'=>'0,95','generation'=>'III'],
['id'=>'318','name'=>'Silver Wind','type_1'=>'Bug','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'60','accuracy'=>'1','generation'=>'III'],
['id'=>'319','name'=>'Metal Sound','type_1'=>'Steel','category'=>'Status','contest'=>'Clever','pp'=>'40','power'=>'0','accuracy'=>'0,85','generation'=>'III'],
['id'=>'320','name'=>'Grass Whistle','type_1'=>'Grass','category'=>'Status','contest'=>'Clever','pp'=>'15','power'=>'0','accuracy'=>'0,55','generation'=>'III'],
['id'=>'321','name'=>'Tickle','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'20','power'=>'0','accuracy'=>'1','generation'=>'III'],
['id'=>'322','name'=>'Cosmic Power','type_1'=>'Psychic','category'=>'Status','contest'=>'Beautiful','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'323','name'=>'Water Spout','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'150','accuracy'=>'1','generation'=>'III'],
['id'=>'324','name'=>'Signal Beam','type_1'=>'Bug','category'=>'Special','contest'=>'Beautiful','pp'=>'15','power'=>'75','accuracy'=>'1','generation'=>'III'],
['id'=>'325','name'=>'Shadow Punch','type_1'=>'Ghost','category'=>'Physical','contest'=>'Clever','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'III'],
['id'=>'326','name'=>'Extrasensory','type_1'=>'Psychic','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'80','accuracy'=>'1','generation'=>'III'],
['id'=>'327','name'=>'Sky Uppercut','type_1'=>'Fighting','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'85','accuracy'=>'0,9','generation'=>'III'],
['id'=>'328','name'=>'Sand Tomb','type_1'=>'Ground','category'=>'Physical','contest'=>'Clever','pp'=>'15','power'=>'35','accuracy'=>'0,85','generation'=>'III'],
['id'=>'329','name'=>'Sheer Cold','type_1'=>'Ice','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'0','accuracy'=>'0,3','generation'=>'III'],
['id'=>'330','name'=>'Muddy Water','type_1'=>'Water','category'=>'Special','contest'=>'Tough','pp'=>'10','power'=>'90','accuracy'=>'0,85','generation'=>'III'],
['id'=>'331','name'=>'Bullet Seed','type_1'=>'Grass','category'=>'Physical','contest'=>'Cool','pp'=>'30','power'=>'25','accuracy'=>'1','generation'=>'III'],
['id'=>'332','name'=>'Aerial Ace','type_1'=>'Flying','category'=>'Physical','contest'=>'Cool','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'III'],
['id'=>'333','name'=>'Icicle Spear','type_1'=>'Ice','category'=>'Physical','contest'=>'Beautiful','pp'=>'30','power'=>'25','accuracy'=>'1','generation'=>'III'],
['id'=>'334','name'=>'Iron Defense','type_1'=>'Steel','category'=>'Status','contest'=>'Tough','pp'=>'15','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'335','name'=>'Block','type_1'=>'Normal','category'=>'Status','contest'=>'Cute','pp'=>'5','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'336','name'=>'Howl','type_1'=>'Normal','category'=>'Status','contest'=>'Cool','pp'=>'40','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'337','name'=>'Dragon Claw','type_1'=>'Dragon','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'80','accuracy'=>'1','generation'=>'III'],
['id'=>'338','name'=>'Frenzy Plant','type_1'=>'Grass','category'=>'Special','contest'=>'Cool','pp'=>'5','power'=>'150','accuracy'=>'0,9','generation'=>'III'],
['id'=>'339','name'=>'Bulk Up','type_1'=>'Fighting','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'340','name'=>'Bounce','type_1'=>'Flying','category'=>'Physical','contest'=>'Cute','pp'=>'5','power'=>'85','accuracy'=>'0,85','generation'=>'III'],
['id'=>'341','name'=>'Mud Shot','type_1'=>'Ground','category'=>'Special','contest'=>'Tough','pp'=>'15','power'=>'55','accuracy'=>'0,95','generation'=>'III'],
['id'=>'342','name'=>'Poison Tail','type_1'=>'Poison','category'=>'Physical','contest'=>'Clever','pp'=>'25','power'=>'50','accuracy'=>'1','generation'=>'III'],
['id'=>'343','name'=>'Covet','type_1'=>'Normal','category'=>'Physical','contest'=>'Cute','pp'=>'25','power'=>'60','accuracy'=>'1','generation'=>'III'],
['id'=>'344','name'=>'Volt Tackle','type_1'=>'Electric','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'120','accuracy'=>'1','generation'=>'III'],
['id'=>'345','name'=>'Magical Leaf','type_1'=>'Grass','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'III'],
['id'=>'346','name'=>'Water Sport','type_1'=>'Water','category'=>'Status','contest'=>'Cute','pp'=>'15','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'347','name'=>'Calm Mind','type_1'=>'Psychic','category'=>'Status','contest'=>'Clever','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'348','name'=>'Leaf Blade','type_1'=>'Grass','category'=>'Physical','contest'=>'Cool','pp'=>'15','power'=>'90','accuracy'=>'1','generation'=>'III'],
['id'=>'349','name'=>'Dragon Dance','type_1'=>'Dragon','category'=>'Status','contest'=>'Cool','pp'=>'20','power'=>'0','accuracy'=>'0','generation'=>'III'],
['id'=>'350','name'=>'Rock Blast','type_1'=>'Rock','category'=>'Physical','contest'=>'Tough','pp'=>'10','power'=>'25','accuracy'=>'0,9','generation'=>'III'],
['id'=>'351','name'=>'Shock Wave','type_1'=>'Electric','category'=>'Special','contest'=>'Cool','pp'=>'20','power'=>'60','accuracy'=>'0','generation'=>'III'],
['id'=>'352','name'=>'Water Pulse','type_1'=>'Water','category'=>'Special','contest'=>'Beautiful','pp'=>'20','power'=>'60','accuracy'=>'1','generation'=>'III'],
['id'=>'353','name'=>'Doom Desire','type_1'=>'Steel','category'=>'Special','contest'=>'Beautiful','pp'=>'5','power'=>'140','accuracy'=>'1','generation'=>'III'],
['id'=>'354','name'=>'Psycho Boost','type_1'=>'Psychic','category'=>'Special','contest'=>'Clever','pp'=>'5','power'=>'140','accuracy'=>'0,9','generation'=>'III']];
define("POKEMON_ATTACKS", $pokemon_attacks);
